---
title: "Dilsher Singh Dhillon"
author: "Dilsher Dhillon"
date: "12/4/2019"
output:
  pagedown::html_resume:
    css: ['css/custom_resume.css', 'css/styles.css', 'resume']
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library(tidyverse)
library(glue)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- TRUE

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R')
```



Aside  
=======================================   

**Contact**       
---------------------------------------    
- <i class="fa fa-envelope"></i> dhillon.dilsher@gmail.com   
- <i class="fa fa-twitter"></i> dhillon_stats  
- <i class="fa fa-link"></i> [Webpage](http://dilsherdhillon.rbind.io/)  


Skills  
---------------------------------------
**Statistics**    <i class="fa fa-infinity"></i>   


Generalized Linear Models  
Heirarchical Models   
Design of Experiments(DOE)  
Bayesian Inference  
Bespoke Statistical Models  
Time-series Regression   


**Software**      <i class="fa fa-code-branch"></i>  

R, Python  
Stan, SQL  
Git, Docker  
Building Docker images to containerize applications and analysis workflows   
Package Development in R    
Unit-testing   
Shiny application development   

**Consulting**     <i class="fa fa-people-carry"></i>  
Experience in statistical consulting      
Gathering key subject expertise from clients  
Working closely with decision makers to frame relevant questions   
Effective communication to non-technical audience    

Main
====================================

Dilsher Singh Dhillon {#title}  
------------------------------------

I'm an applied statistician with expertise in applying both traditional and modern statistical methods to solve business problems.  I'm an advocate for reproducible workflows and an avid user of R markdown documents and docker containers.  I'm looking for opportunities where I can leverage my statistics training to quantify uncertainty to aid in better decision making.  



Disclaimer   
------------------------------------  
Permanent US Resident  

Education {data-icon=graduation-cap}
------------------------------------

### Texas A&M University  

Master's in Statistics   

College Station, TX     

2015 - 2017   

Summa Cum Laude   

### Texas A&M University   

Master's in Biotechnology  

College Station, TX     

2010 - 2012    

Cum Laude  

### Panjab University   

Bachelor of Engineering  

Chandigarh, India   

2006 - 2010  

Work Experience  {data-icon=briefcase}  
------------------------------------  

### Shell International Exploration and Production   

Statistical Consultant      

Houston, TX  

March 2019 - Present  

- *Shell commercial products*       
  - Help improve the line of products offered by Shell by assisting researchers implement sensible experimental design  
  - Analysis of randomized experiments and higher-order factorial designs  
  - Building data models from complex unstructured data to conduct meaningful statistical analysis  
  - Effective communication of results to stakeholders aiding in optimum decision making  
- *Drilling operations*  
  - Delivered a well calibrated probabilistic map of a region of interest that indicates risk of encountering hazards     
  - Provide statistical input to the business unit on decisions to turn work on/off   
  - Building interpretable machine learning models to drive decision making  
- Developing experimental methods to make inferences on important metrics 


### Baylor College of Medicine  

Statistician        

Houston, TX   

2018 - 2019   

- *Identifying risk factors for poor outcomes in co-infected TB-HIV patients*    
  - Worked with clinicians in Africa to extract longitudunal data for ~25000 subjects  
  - Developed a statistical model to understand risk factors that are associated with poor TB outcome - which leads to better patient management guidelines for high risk countries.  
- *Studying underlying epigenetic mechanism of TB infection*  
  - Processed methylation data from EPIC arrays consisting of ~850,000 individual probes 
  - Assisted physician researchers with bioinformatic analysis of methylation and flow cytometry analysis  
  - Automated a pipeline in Python for merging of patient data from clinical research forms in eSwatini   

### MD Anderson Cancer Center 

Research Investigator       

Houston, TX    

2013 - 2018   

- Promoted to a supervisory capacity to oversee assay development of novel biomarkers and testing of in-house and commercial
assays in clinical samples for validation   
- Managed the Specimen Manger database for recording subject characteristics, bio-specimen banking and inventory and multicenter study inventory for the Lung Cancer Early Detection trial 


